var STYLE_CELL_STOPPED = {};
STYLE_CELL_STOPPED[mxConstants.STYLE_STROKECOLOR] = '#FF0000';
STYLE_CELL_STOPPED[mxConstants.STYLE_STROKEWIDTH] = 2;

var STYLE_NO_CHECK_SELECTED = {};
STYLE_NO_CHECK_SELECTED[mxConstants.STYLE_STROKECOLOR] = '#FFCC00';
STYLE_NO_CHECK_SELECTED[mxConstants.STYLE_STROKEWIDTH] = 2;

var STYLE_ACTIVE_CHECK = {};
STYLE_ACTIVE_CHECK[mxConstants.STYLE_STROKECOLOR] = '#00C800';
STYLE_ACTIVE_CHECK[mxConstants.STYLE_STROKEWIDTH] = 5;
